---
- hosts: localhost
  tasks:
  - name: "Start nginx container"
    docker_container:
      name: training-nginx
      image: nginx
      ports:
        - "80:80"

  - name: "Start basic ubuntu container"
    docker_container:
      name: training-ubuntu
      image: ubuntu
      command: sleep infinity

  - name: "Start jenkins container"
    docker_container:
      name: training-jenkins
      image: jenkins/jenkins
      ports:
        - "8080:8080"
        - "443:443"
        - "50000:50000"
